Header
volirim/React_lab pull request #1
Opened 2021-11-25 12:20 UTC by volirim

Added header with routes and footer with links

2021-11-25 12:43 UTC, StasKhitrich requested changes

2021-11-25 12:43 UTC, StasKhitrich commented on src/components/footer/footer.scss
> +  height: 96px;
Никаких фикс высот без острой необходимости. Высота контейнера основывается на паддингах и внутренних элементах. С фикс высотами кашу не сваришь и адаптив не сделаешь нормально

2021-11-25 12:43 UTC, StasKhitrich commented on src/components/footer/footer.scss
> +  height: 50px;
На картинках можно использовать высоту, но, хоть адаптив и не часть лабы, но картинки лучше ограничивать с помощью width: 100%; max-width: 50px;
Таким образом при сужении экрана, картинка будет не более 50px, но начнет уменьшаться, если есть необходимость.

2021-11-25 12:43 UTC, StasKhitrich commented on src/components/footer/footer.scss
> +.footer-container {
В целом претензия к подходу с полностью глобальными стилями. Для компонентов делай модульные стили или emotions/styled-components

2021-11-25 12:43 UTC, StasKhitrich commented on src/components/header/header.scss
> +.header-container {
Тоже самое, что и с футером. Компонентные стили лучше делать локальными с помощью [modules](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/)

2021-11-25 12:43 UTC, StasKhitrich commented on src/components/header/header.scss
> +  height: 96px;
Та же проблема, фикс высоты

2021-11-25 12:43 UTC, StasKhitrich commented on src/components/main/mainPage.scss
> +  min-height: calc(100vh - 96px - 96px);
[5 способов прижать футер к низу](https://sgeek.pro/blog/coding/2019-05-30-5-sposobov-kak-prizhat-footer-k-nizu-stranicy.html)

2021-11-25 12:43 UTC, StasKhitrich commented on src/main.tsx
> +      <Header />
Не обязательно, но советую создать компонент Layout и общие элементы всех страниц выкинуть туда. Обернуть им Routes. Если появится сайдбар или типа того, добавишь это в него. 
Нужную страницу выводить как контент layout с помощью children проперти можно
[Пример](https://dev.to/olenadrugalya/layout-component-and-why-we-use-it-in-react-d8b)

2021-11-26 07:31 UTC, volirim commented on src/components/footer/footer.scss
> +  height: 96px;
исправлено

2021-11-26 07:31 UTC, volirim commented on src/components/footer/footer.scss
> +  height: 50px;
исправлено

2021-11-26 09:09 UTC, volirim commented on src/components/header/header.scss
> +  height: 96px;
исправлено

2021-11-26 09:09 UTC, volirim commented on src/components/main/mainPage.scss
> +  min-height: calc(100vh - 96px - 96px);
исправлено

2021-11-26 09:11 UTC, volirim commented on src/components/header/header.scss
> +.header-container {
исправлено

2021-11-26 09:12 UTC, volirim commented on src/main.tsx
> +      <Header />
пока не совсем понимаю, как это работает, как пойму, переделаю. Пока что пусть остается так

2021-11-26 10:07 UTC, StasKhitrich approved these changes

2021-11-26 10:07 UTC, merged