Fourth lab
volirim/React_lab pull request #3
Opened 2021-12-01 12:41 UTC by volirim

2021-12-01 13:09 UTC, StasKhitrich requested changes

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/header/modules/navMenu/menu.tsx
> +          if (component.name === "Products") {
Нет, слишком лобовое решение)
Работать должно так, что если у тебя есть вложенные pages или routes (например) в маршруте, то тут автоматом должно выводится подменю.
Для того чтобы такого добиться, сделай чтобы в navmenu компонент необходимо было прокидывать массив страниц. В основное меню ты прокидываешь страницы, проходишься по ним и если есть вложенные, то опять вызываешь этот же компонент. 
В упрощенном варианте можно сделать не повторный вызов компонента, а просто вывод этого подменю.
[Пример](https://www.bitovi.com/blog/recursive-react-components)

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/header/modules/navMenu/menu.tsx
> +                  <NavLink to="products/pc" className={nav.item}>
Ссылки хранятся в отдельном файле с ссылками и ты их импортируешь

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/header/modules/navMenu/menu.tsx
> +                  <NavLink to="products/pc" className={nav.item}>
pc/playstation/xbox и будут вложенными урлами при наличии которых будет выводится подменю (дополнение к комментарию про лобовое решение)

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/categoriesBlock/categories.tsx
> +        <NavLink to="products/pc" className={categories.category}>
Ссылки в отдельный файл

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/gameCard/game.module.scss
> +  max-height: 350px;
А если текста будет слишком много? Или картинка выше нужного?
Правильно сделанная полоса для вывода карточек (row) на флексах сама растянет карточки до высоты максимально высокой карточки
[Пример](https://mono.software/2020/07/29/equal-height-cards-with-flexbox/)

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/gameCard/game.module.scss
> +  height: 75%;
Сделай картинку фоном дива, а диву задай высоту. Картинке размер cover и она будет обрезаться и масштабироватсья сама. Или object-fit. Сами картинки, ограничивая по высоте, будут вести себя плохо

2021-12-01 13:09 UTC, StasKhitrich commented on src/types/Mockapi.ts
> +type ApiObject = {
Плохое название, внутри продукт описан? А название слишком абстрактное для такого интерфейса

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/gameCard/gameCard.tsx
> +        <div className={card.rating}>{props.rating} stars</div>
Отдельным компонентом с звёздами

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/gameCard/gameCard.tsx
> +        <div className={card.rating}>{props.rating} stars</div>
Отдельным компонентом с звёздами
Звёзды в интернете есть: [Пример](https://upload.wikimedia.org/wikipedia/commons/a/a3/Orange_star.svg)

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/gameCardsBlock/gameCards.module.scss
> +.bottom {
Слишком абстрактные классы у тебя. Понятное дело, у тебя локальные компонентные стили, но всё же, можно называть более понятно человеку. А ещё лучше, стараться соблюдать БЭМ подход даже в таком случае

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/gameCardsBlock/gameCardsBlock.tsx
> +          {cards
Подготавливай логику до рендера, хотя-бы фильтрацию. Чем меньше логики в шаблонах - тем лучше

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/gameCardsBlock/gameCardsBlock.tsx
> +  if (category) {
Не вижу необходимости в этом дополнительном рендере и дублировании кода

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/homePage.tsx
> +import "./mainPage.scss";
Сделай модульными стилями. Такой импорт приведет к тому, что эти стили остануться глобальными для проекта и будут доступны каждому компоненту. Либо выноси общие стили в глобальные куда-то в ассеты и не храни рядом с компонентами

2021-12-01 13:09 UTC, StasKhitrich commented on src/components/main/signUpPage.tsx
> +import "./mainPage.scss";
Такие стили стоит подключать как глобальные и их не нужно подключать в каждом файле, такой импорт сам по себе зарегистрирует их глобально

2021-12-02 10:46 UTC, volirim commented on src/components/header/modules/navMenu/menu.tsx
> +          if (component.name === "Products") {
пофиксил

2021-12-02 10:46 UTC, volirim commented on src/components/header/modules/navMenu/menu.tsx
> +                  <NavLink to="products/pc" className={nav.item}>
пофиксил

2021-12-02 10:47 UTC, volirim commented on src/components/header/modules/navMenu/menu.tsx
> +                  <NavLink to="products/pc" className={nav.item}>
пофиксил

2021-12-02 10:50 UTC, volirim commented on src/components/main/categoriesBlock/categories.tsx
> +        <NavLink to="products/pc" className={categories.category}>
пофиксил

2021-12-02 13:54 UTC, volirim commented on src/types/Mockapi.ts
> +type ApiObject = {
исправил

2021-12-02 14:02 UTC, volirim commented on src/components/main/gameCard/game.module.scss
> +  height: 75%;
исправил на object-fit

2021-12-02 14:07 UTC, volirim commented on src/components/main/gameCard/game.module.scss
> +  max-height: 350px;
исправил

2021-12-02 14:58 UTC, volirim commented on src/components/main/gameCardsBlock/gameCardsBlock.tsx
> +          {cards
исправил

2021-12-02 15:01 UTC, volirim commented on src/components/main/gameCardsBlock/gameCards.module.scss
> +.bottom {
поправил

2021-12-02 15:01 UTC, volirim commented on src/components/main/gameCardsBlock/gameCardsBlock.tsx
> +  if (category) {
поправил

2021-12-02 16:22 UTC, volirim commented on src/components/main/homePage.tsx
> +import "./mainPage.scss";
вынес в assets/globalStyles

2021-12-02 16:22 UTC, volirim commented on src/components/main/signUpPage.tsx
> +import "./mainPage.scss";
исправил

2021-12-02 17:00 UTC, volirim commented on src/components/main/gameCard/gameCard.tsx
> +        <div className={card.rating}>{props.rating} stars</div>
сделал

2021-12-02 17:00 UTC, volirim commented on src/components/main/gameCard/gameCard.tsx
> +        <div className={card.rating}>{props.rating} stars</div>
сделал

2021-12-03 09:00 UTC, StasKhitrich requested changes

2021-12-03 09:00 UTC, StasKhitrich commented on src/components/dropdownMenu/dropDownMenu.tsx
> +  const [hover, setHover] = useState(false);
Нет, тут не нужен JS для организации меню и ховеров, это всё делается чистой вёрсткой.
Сделал пример, разбери и повтори у себя: [Пример](https://stackblitz.com/edit/react-pwilb3?file=src%2Findex.js)
Там уже есть и подсветка активного маршрута, и вывод подменю с ховером стилями.
Как переделаешь, посмотрим снова

2021-12-03 09:00 UTC, StasKhitrich commented on src/utils/CardsCategoriesSplitter.tsx
> +  if (category) {
Не нужна тут такая логика. Фильтрацию вынеси в тело компонента и произведи заранее подготовив данные. В самом шаблоне останется вывод уже подготовленных данных

2021-12-03 09:00 UTC, StasKhitrich commented on src/components/main/categoriesBlock/categories.tsx
> +        {routes[1].options.map((el) => (
А если очередность элементов массива поменяется? Тут просто собьется логика вся. В примере который я сделал есть вариант как это обойти

2021-12-03 12:03 UTC, volirim commented on src/components/main/categoriesBlock/categories.tsx
> +        {routes[1].options.map((el) => (
исправил

2021-12-03 12:03 UTC, volirim commented on src/components/dropdownMenu/dropDownMenu.tsx
> +  const [hover, setHover] = useState(false);
исправил

2021-12-03 15:58 UTC, StasKhitrich requested changes

2021-12-03 15:58 UTC, StasKhitrich commented on src/api/mockapiData.tsx
> +  _cards: GameCardType[],
Зачем первый аргумент здесь? Он не используется внутри функции

2021-12-03 15:58 UTC, StasKhitrich commented on src/api/mockapiData.tsx
> +  setCard: React.Dispatch<React.SetStateAction<GameCardType[] | never[]>>,
Зачем never[]? Если заслать пустой массив, то он тоже подойдёт под первый пункт

2021-12-03 15:58 UTC, StasKhitrich commented on src/api/mockapiData.tsx
> +  setCard: React.Dispatch<React.SetStateAction<GameCardType[] | never[]>>,
Засылать функцию по установке данных внутрь метода для получения данных - плохая практика. Дожидайся ответа от метода getGamesData и внутри компонента устанавливай данные в стейт.
Функция для получения данных не должна ничего знать об окружении где её применяют, чем меньше смешиваешь логику - тем лучше

2021-12-03 15:58 UTC, StasKhitrich commented on src/components/header/modules/navMenu/menu.module.scss
>    width: 30em;
Меню само займет ширину на основании элементов внутри

2021-12-03 15:58 UTC, StasKhitrich commented on src/constants/menus.ts
> +    sub: [ROUTES.products.pc, ROUTES.products.playstation, ROUTES.products.xbox],
У тебя рядом лежит categoryMenu файл. 
А этот файл назван menus. Почему бы не объединить 2 файла в общем menus?
Также ты сможешь sub не дублировать, перечисляя все категории, а просто использовать меню categoriesMenu.

2021-12-03 15:58 UTC, StasKhitrich commented on src/types/MenuElementInterface.ts
> +  sub?: typeof HEADER_MENU;
Опиши отдельный тип для подменю

2021-12-03 15:58 UTC, StasKhitrich commented on src/utils/Cards.tsx
> +  if (category) {
Ты по прежнему делаешь if else в шаблоне, почему эту фильтрацию не вынести в логику компонента ДО рендера? Ты выводишь однотипные данные в одном формате, но в первом случае ты фильтруешь, а во втором не фильтруешь. Профильтруй заранее и не дублируй повторы в рендере.
map можно делать в шаблоне, это реактовский способ вывода компонентов на основе данных, но подготовка, типа фильтров, должна делаться ДО

2021-12-03 15:58 UTC, StasKhitrich commented on src/api/mockapiData.tsx
> +  return fetch(`https://61a36f44d5e8330017292010.mockapi.io/${path}`)
Кстати, апишные урлы тоже можно в константы вынести. Хотя-бы уникальный ID пользователя для запроса. Если прокачаться хочешь, почитай про env файлы и константы проектные (не всё там хранить стоит, только строки). Почти во всех проектах есть .env файл. Это можно не исправлять, просто советую лучшую практику

2021-12-06 09:54 UTC, volirim commented on src/api/mockapiData.tsx
> +  _cards: GameCardType[],
исправлено

2021-12-06 09:55 UTC, volirim commented on src/api/mockapiData.tsx
> +  setCard: React.Dispatch<React.SetStateAction<GameCardType[] | never[]>>,
исправлено

2021-12-06 10:14 UTC, volirim commented on src/api/mockapiData.tsx
> +  setCard: React.Dispatch<React.SetStateAction<GameCardType[] | never[]>>,
исправлено

2021-12-06 10:16 UTC, volirim commented on src/components/header/modules/navMenu/menu.module.scss
>    width: 30em;
исправил

2021-12-06 10:25 UTC, volirim commented on src/constants/menus.ts
> +    sub: [ROUTES.products.pc, ROUTES.products.playstation, ROUTES.products.xbox],
исправил

2021-12-06 10:35 UTC, volirim commented on src/types/MenuElementInterface.ts
> +  sub?: typeof HEADER_MENU;
исправил

2021-12-06 12:31 UTC, volirim commented on src/utils/Cards.tsx
> +  if (category) {
исправлено

2021-12-06 12:35 UTC, volirim commented on src/api/mockapiData.tsx
> +  return fetch(`https://61a36f44d5e8330017292010.mockapi.io/${path}`)
пока что просто вынес в константы

2021-12-06 12:56 UTC, StasKhitrich approved these changes

2021-12-06 12:56 UTC, StasKhitrich commented on src/components/header/modules/navMenu/menuElement/menuElement.tsx
> +  const classesList = [classes.item].join(" ");
У тебя тут всего 1 класс, массив не нужен

2021-12-06 12:56 UTC, StasKhitrich commented on src/components/main/homePage.tsx
> +      const data = await getGamesData("topgames");
Тут можно await getGamesData сразу в setCard написать. Переменная в принципе лишняя, данные не переиспользуются

2021-12-06 12:56 UTC, StasKhitrich commented on src/components/main/productsPage.tsx
> +      const data = await getGamesData("games");
Тоже самое с await и setData

2021-12-06 12:56 UTC, StasKhitrich commented on src/components/search/searchInput/searchInput.module.scss
> +  height: 35px;
Уже говорил, что height лучше не использовать. Можно отступы внутри добавить (padding)

2021-12-06 12:56 UTC, merged