end fifth lab
volirim/React_lab pull request #4
Opened 2021-12-10 15:56 UTC by volirim

пока что без local storage, очень нужно ревью, чтобы я точно знал что и как исправлять.

2021-12-10 19:02 UTC, StasKhitrich requested changes

2021-12-10 19:02 UTC, StasKhitrich commented on src/api/postMockapiData.ts
> +    fetch(`${MOCK_API_URL}user`, {
Лучше хранить без слеша (/) урлы в константах. Если так сделаешь, то в местах использования читабельность станет намного лучше:
`${MOCK_API_URL}/user`
`${MOCK_API_URL}/products`

2021-12-10 19:02 UTC, StasKhitrich commented on src/api/postMockapiData.ts
> +  if (user) {
Почему у тебя аргумент может быть типа void? 
Вообще, void используется когда функция ничего не возвращает:
`() => void`
Оставь только нужный тип и тогда у тебя отпадёт необходимость в этом if с проверкой на пользователя. Тайпскрипт не даст вызвать функцию не заслав пользователя

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +
Лишняя пустая строка

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +const MainComponent = function () {
Компонент должен иметь название такое же как и имя файла

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +  const updateUserStatus = (newStatus: boolean | ((prevState: boolean) => boolean)) => setUserStatus(newStatus);
Не нужная функция, setUserStatus делает тоже самое.
+ альтернативный тип аргумента newStatus в виде функции вызовет ошибку, ведь внутри updateUserStatus у тебя нет проверки на функцию и её вызова. Ты пытаешься в state<boolean> пропихнуть значение типа function, что ошибочно

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +  if (!userStatus) {
Опять, вредная привычка и это не правильно когда у компонента есть 2 альтернативных рендера. У тебя шаблон отличается лишь частично и нет нужды делать полностью отдельный рендер внутри компонента.
Если есть необходимость сделать совсем различные рендеры, то делай подкомпоненты и выводи их в зависимости от условия

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +            <Route path="/" element={<Home modalIsOpen={false} updateUserStatus={updateUserStatus} />} />
modalIsOpen всегда false? В чём смысл тогда? Также, пропсы стоит расписывать более понятно. Что за модалка?

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +            <Route path="/login" element={<Home modalIsOpen updateUserStatus={updateUserStatus} />} />
Если там, внутри, по умолчанию false, то незачем было выше писать modalIsOpen={false}, а если там внутри true по умолчанию, то тут незачем писать modalIsOpen

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +          <Route path="/products/" element={<Products />}>
В конце маршрута слеши не нужны, они лишь для начала и разделения частей маршрута

2021-12-10 19:02 UTC, StasKhitrich commented on src/app.tsx
> +            <Route path=":platform" />
А тут надо добавить слеш в начале (когда уберешь его выше с родительского маршрута)

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/header/header.tsx
> +      <NavMenu menu={userStatus ? HEADER_MENU_AUTHORISED : HEADER_MENU} />
Код чище станет, если будешь такое готовить до рендера в теле компонента. Обычную константу сделать и в шаблоне её использовать

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/main/homePage.tsx
> +const Home = function ({ modalIsOpen, updateUserStatus }: HomePagePropsInterface) {
Название компонента и файла отличаются

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/main/homePage.tsx
>    const [cards, setCard] = useState<GameCardType[] | never[]>([]);
Нет смысла писать never[]. 
Пустой массив подойдёт и под GameCardType[]

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/main/homePage.tsx
>    const [name, setName] = useState("");
Не понимаю этот стейт. Что за имя? Для чего оно? Почему оно пробрасывается в GameCardsBlock? Уверен, что тебе нужен этот стейт?
GameCardsBlock - звучит как компонент для вывода карточек. Сами карточки, в идеале, отдельный компонент. По логике. никакого имени там нет

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/main/homePage.tsx
> +  if (modalIsOpen) {
Опять отдельный рендер с условием. Это плохая практика. Данные готовятся до рендера, рендер - всего один. Внутри рендера можно делать условия. Если рендер действительно нуждается в совершенно разном содержимом в зависимости от условия (не частичный), то делаешь подкомпоненты

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/main/homePage.tsx
> +        <Search updateName={updateName} />
Я полагаю, что ты вводишь имя в инпуте-поиске и в зависимости от этого фильтруешь карточки с товаром. Ну так это стоит делать в этом компоненте. Ты фильтруешь карточки в зависимости от введённого пользователем значения.
+ в задачах было уточнение, что поиск работает с запросами на сервер. Инпут работает с debounce 300 миллисекунд (не делает поиск пока ввод не закончен). Фильтрация должна сопровождаться запросом. Продуктов для вывода может быть слишком много и на реальных сайтах фильтрация происходит не на фронте

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/main/profilePage.tsx
> +const Profile: React.FC = function () {
+ Название файла лучше делать с большой буквы. ProfilePage.tsx (на весь проект распространи)
+ Название компонента ProfilePage.tsx, если это страница на которую опирается маршрут, то подписывай компонент соответствующе (на весь проект распространи)
+ Уже вижу странность, у тебя в папке components хранится какой-то main с страницами. Под страницы/контейнеры(умные компоненты с получением данных) делается отдельная папка containers/pages/views рядом с components

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/modal/Modal.tsx
> +const ModalRoot = function ({ updateUserStatus }: SetUserStatusInterface) {
Ты можешь сделать отдельную папку в components, например - modals. 
В ней хранить модалки.
Базовый компонент можно вынести в подпапку components/base/ModalBase и назвать ModalBase.tsx.
Или просто components/ModalBase/ModalBase.tsx
Сейчас же у тебя опять компонент называется не по названию файла

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/modal/Modal.tsx
> +  const modalElement = document.getElementById("modal")!;
Переменная излишняя. У тебя только одно место где это необходимо, можешь прям вторым параметром написать в портале document.getElement...

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/modal/Modal.tsx
> +  document.body.setAttribute("style", "overflow: hidden");
1. Напрямую с стилями работать не нужно, все изменения стилей на странице должны производится через классы. Делай глобальный класс с нужными свойствами и подходящим именем и добавляй его элементу или убирай по необходимости (редкие кейсы нуждаются в отдельных свойствах css без классов)
2. Для работы с элементами лучше использовать document.querySelector, getElementById - редкая штука. Старайся в принципе ID не использовать, не лучшая практика
3. Вынеси логику по добавлению класса элементу в utils директорию. Например, будет метод setClass принимающий селектор элемента на который надо навесить класс и название класса/классов которые надо навесить
4. Также сделай там утилиту для удаления класса

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/modal/Modal.tsx
> +        <NavLink to="/">
Неправильно. Зачем тебе тут NavLink на главную? Тут должен быть крестик для закрытия модалки и всё.
О том как сделать модалки:
+ ModalBase - компонент выводящий окошко и перекрывающее фоном интерфейс ([примеры с бутстрапа](https://getbootstrap.com/docs/4.0/components/modal/)). Базовый компонент, выводит children prop в контенте модального окна. То есть, по сути, это бесполезный компонент без переданной логики которую надо вывести. 
Ты можешь сделать в ней заготовленный header с кнопкой закрытия и дополнительный prop с заголовком, но не более (чаще всего).
Также, в базовой модалке, можешь сделать чтобы по нажатию на её фон она закрывалась
+ ModalSignIn - компонент использующий ModalBase и содержащий логику конкретной модалки. Ты пишешь внутри `<ModalBase> Какой-то контент, кнопки, логика </ModalBase>`
+ ModalSignUp - такой же компонент-надстройка, но уже со своей логикой
Потом уже эти надстройки и используешь

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/modal/modalWindow/ModalWindow.tsx
> +const ModalWindow = function ({ updateUserStatus }: SetUserStatusInterface) {
Этот компонент в принципе неправильный и опять двойной-тройной рендер в рамках одного компонента. 
Я описал про модалки выше. В интернете много примеров про модалки. 
Все модалки - отдельные компоненты. Нужные используются в нужных местах по необходимости.

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/modal/modalWindow/ModalWindow.tsx
> +// eslint-disable-next-line consistent-return
Так низя)

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/signInModal/signInModal.tsx
> +  return (
По сути, вот тут у тебя будет вызов BaseModal и туда ты передаешь формочку ниже и всё

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/modal/modalWindow/modalWindow.module.scss
> +  width: 65%;
Не думаю, что это нужно. 65% ширина - странно звучит

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/signOutModal/signOutModal.module.scss
> +  padding: 3%;
Паддинги в процентах - не лучшая практика. Лучше использовать пиксели и менять через медиа запросы по необходимости

2021-12-10 19:02 UTC, StasKhitrich commented on src/components/signUpModal/signUpModal.tsx
> +    if (await onSubmitRegister(data, updateUserStatus)) {
Вынеси в константу. В условиях лучше await и логику не писать, условие стоит заранее оформлять

2021-12-10 19:02 UTC, StasKhitrich commented on src/elements/inputText.tsx
> +const InputText = function ({ register, placeholder }: InputTextInterface) {
Мне не нравится такой подход. 
У тебя должен быть базовый компонент Input. В случае с Input нет смысла делать InputBase, ведь надстроек не будет.
Ты должен передавать сюда параметр type и просто менять тип инпута на нужный. При твоем подходе ты будешь создавать отдельный компонент под инпут с паролем и другие.

2021-12-10 19:02 UTC, StasKhitrich commented on src/elements/inputText.tsx
> +    <div className="inputWrapper">
Мне кажется этот див лишний. Базовый инпут стоит вставлять либо сам по себе, либо обёрнутый в label и с выводом подписи. input обязан принимать prop name для формы и работы, это обязательный параметр инпутов по сути.

2021-12-10 19:02 UTC, StasKhitrich commented on src/elements/inputText.tsx
> +import "./inputText.scss";
Переделай компонент на модульные стили

2021-12-10 19:02 UTC, StasKhitrich commented on src/elements/inputText.tsx
> +import InputTextInterface from "@/types/inputTextInterface";
Кстати, локальные типы компонентов можно хранить в компоненте

2021-12-10 19:02 UTC, StasKhitrich commented on src/index.html
> +    <div id="modal"></div>
modals - у тебя же несколько компонентов в одном портале может быть

2021-12-10 19:02 UTC, StasKhitrich commented on src/main.tsx
>  import "./styles/main.css";
В чём смысл двух файлов main с стилями?
Один с препроцессором, второй без

2021-12-10 19:02 UTC, StasKhitrich commented on src/main.tsx
>  import "./assets/globalStyles/mainPage.scss";
Если mainPage стили для ВСЕХ страниц и это действительно глобальные стили, то просто импортируй их внутри main.scss чтобы сократить количество импортов в main.tsx. У тебя должен импортировать в main.tsx лишь 1 файл стилей, который импортирует в себя всё остальное. + переименуй файл, если это общие стили.
И вот пример структуры глобальных файлов стилей: [ТыЦ](https://qna.habr.com/q/741337)
Если это стили для конкретной главной страницы, то перенеси это в модульные стили конкретного компонента главной страницы.

2021-12-10 19:02 UTC, StasKhitrich commented on src/main.tsx
> +    return <MainComponent />;
App и есть глобальный/главный компонент и точка входа.
Точнее, у тебя должен был быть main.tsx с монтированием приложения и App.tsx компонент в котором маршрутизация хранится и тд. Почему-то твоя структура изменилась и отошла от этой практики в сторону аналогичной схемы, но с своим компонентом MainComponent.
И откуда взялась приписка Component? Везде не пишешь и тут не стоит

2021-12-10 19:02 UTC, StasKhitrich commented on src/styles/main.scss
> +  padding: 5%;
Процентный паддинг - не лучшая практика. Проверь всё

2021-12-10 19:02 UTC, StasKhitrich commented on src/styles/main.scss
> +#modal > body {
Внутри #modal не может быть тега body

2021-12-10 19:02 UTC, StasKhitrich commented on src/styles/main.scss
> +.form {
Разбей глобальные стили на подфайлы и повыноси всё в разные файлы. Типа элементы форм, хелперы, миксины.
**Сделай отдельный файл под цвета и импортируй его в нужные компоненты (стили компонента) и используй переменные. Это есть на всех проектах, привыкай**

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signInValidation.ts
> +export default onSubmitLogin;
Ну нужен дефолтный импорт, у тебя сверху обычный импорт, сделай такой же и у второго метода

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signInValidation.ts
> +export const loginValidation = (data: UserLoginInterface, response: UserServerInterface[]) => {
Думаю, имеет смысл сделать папку validators рядом с utils. Там сможешь хранить отдельные валидаторы

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signInValidation.ts
> +  updateUserStatus: { (value: SetStateAction<boolean>): void; (arg0: boolean): void }
Какая-то непонятная конструкция, это работает вообще? По-моему тут что-то сломано

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signInValidation.ts
> +  updateUserStatus(loginValidation(data, response));
Плохая практика по передаче метода изменения стейта наружу, вне реакта. 
Ты можешь выносить запросы к БД или какую-то вспомогательную логику, но изменение стейтов должно происходит наглядно прямо в компонентах

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signUpValidation.tsx
> +const validateRegisterData = (
validate подразумевает возврат true/false
А у тебя из функции вообще ничего может не вернутся при каком-то условии. Переделай чтобы валидатор - валидировал. Обработку данных лучше делать в методах transform или типа того

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signUpValidation.tsx
> +    !filteredData.length &&
Очень сложное условие. Вынеси из if в константу. А эти проверки регулярками можно вынести в отдельные методы. В утилитах можно создать файл под проверки регулярками

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signUpValidation.tsx
> +      login: data.login.toLowerCase(),
Чуть выше ты уже делаешь эту процедуру, можно сохранить data.login.toLowerCase куда-то и переиспользовать в условии и тут

2021-12-10 19:02 UTC, StasKhitrich commented on src/utils/signUpValidation.tsx
> +    updateUserStatus(true);
Изменение стейта снаружи компонентов реакта - плохая практика

2021-12-13 09:03 UTC, volirim commented on src/api/postMockapiData.ts
> +    fetch(`${MOCK_API_URL}user`, {
исправил

2021-12-13 09:09 UTC, volirim commented on src/app.tsx
> +
исправил

2021-12-13 09:10 UTC, volirim commented on src/app.tsx
> +const MainComponent = function () {
исправил

2021-12-13 09:16 UTC, volirim commented on src/app.tsx
> +  const updateUserStatus = (newStatus: boolean | ((prevState: boolean) => boolean)) => setUserStatus(newStatus);
исправил

2021-12-13 09:29 UTC, volirim commented on src/app.tsx
> +            <Route path=":platform" />
если я добавляю слеш в начале, то все ломается

2021-12-13 09:30 UTC, volirim commented on src/app.tsx
> +            <Route path=":platform" />
а без слеша все хорошо работает

2021-12-13 09:39 UTC, volirim commented on src/components/main/homePage.tsx
>    const [name, setName] = useState("");
это имя игры, стейт нужен для поиска по имени игры, я поправил название

2021-12-20 09:14 UTC, StasKhitrich requested changes

2021-12-20 09:14 UTC, StasKhitrich commented on src/MainApp.tsx
> +          {/* <Route path="*" element={<Navigate to="/" />} />; */}
Почему убрал обработку всех остальных маршрутов? Под такую страницу создается NotFound страница

2021-12-20 09:14 UTC, StasKhitrich commented on src/MainApp.tsx
> +                <HocRoute Child={Profile} updateUserStatus={setUserStatus} />
Мне кажется у тебя не правильная структура.
PrivateRoute должен принимать те же параметры, что и обычный роут, но + условие. 
То есть тебе надо прокидывать в PrivateRoute компонент и путь за который маршрут будет отвечать + условие при котором маршрут будет активен. То есть тебе не нужен HocRoute отдельный, всё это работа PrivateRoute

2021-12-20 09:14 UTC, StasKhitrich commented on src/api/postMockapiData.ts
> +const sendUserData = (user: UserLoginInterface) => {
Название метода createUser

2021-12-20 09:14 UTC, StasKhitrich commented on src/api/postMockapiData.ts
> +    fetch(`${MOCK_API_URL}/user`, {
Возврат запроса

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/main/gameCard/game.module.scss
>    box-shadow: 1px 0 7px 5px purple;
Цвета все в переменные

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/modal/ModalBase.tsx
> +    <div className={modal.container}>
Закрытие по клику

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/modals/signInModal/SignInModal.tsx
> +  const handleClick = () => {
В утилиты

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/modals/signInModal/SignInModal.tsx
> +        <InputText register={register("login")} placeholder="login" type="text" />
Input без Text

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/modals/signInModal/SignInModal.tsx
> +        <label className="formTitle">Authorisation</label>
Можешь Label внутрь инпут компонента засунуть (не обязательно)

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/modals/signUpModal/navigateConstant.ts
> +  if (status) {
Сократи до return status или !!status

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/search/searchInput/searchInput.tsx
> +  const delayedFunc = debounce(async (e) => {
Попробуй выпилить лодаш и вставь кастомный дебоунс (храни в утилитах)

2021-12-20 09:14 UTC, StasKhitrich commented on src/components/search/searchInput/searchInput.tsx
>        className={input.input}
Импортируемые классы (из стилей компонента) лучше сохранять в classes или styles переменную, чтобы не было таких моментов как input.input

2021-12-20 09:14 UTC, StasKhitrich commented on src/constants/modalList.tsx
> +  nothing: () => <></>,
Это не модалка, но хранится в MODAL_LIST

2021-12-20 09:14 UTC, StasKhitrich commented on src/utils/CategoryFilter.tsx
> +const FilterCategories = function ({ cards, category }: cardsBlockType) {
Как обсуждали, метод изменить. Логику с jsx надо хранить только в компонентах. Фильтрацию можешь вынести в утилиты. Можешь создать отдельный файл filters и там хранить все методы общие для фильтрации чего либо, но обработку результатов фильтрации оставить в компонентах

2021-12-20 09:14 UTC, StasKhitrich commented on src/utils/setClass.ts
> +function setClass(selector: string, classes: string) {
Название файла в classes

2021-12-20 13:38 UTC, volirim commented on src/components/main/gameCard/game.module.scss
>    box-shadow: 1px 0 7px 5px purple;
все повторяющиеся цвета уже в переменных

2021-12-20 14:56 UTC, volirim commented on src/constants/modalList.tsx
> +  nothing: () => <></>,
так это фрагмент, который появляется при отстутствии модалки, я могу это переписать, но будет больше кода, чем если бы я оставил это так

2021-12-20 18:15 UTC, StasKhitrich approved these changes

2021-12-20 18:15 UTC, merged